# Generated by Django 3.2.9 on 2021-11-09 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
